/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRecipesRouteImport } from './routes/docs/recipes'
import { Route as DocsRecipeRouteImport } from './routes/docs/recipe'
import { Route as DocsManualInstallRouteImport } from './routes/docs/manual-install'
import { Route as DocsInstallRouteImport } from './routes/docs/install'

const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRecipesRoute = DocsRecipesRouteImport.update({
  id: '/docs/recipes',
  path: '/docs/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRecipeRoute = DocsRecipeRouteImport.update({
  id: '/docs/recipe',
  path: '/docs/recipe',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsManualInstallRoute = DocsManualInstallRouteImport.update({
  id: '/docs/manual-install',
  path: '/docs/manual-install',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsInstallRoute = DocsInstallRouteImport.update({
  id: '/docs/install',
  path: '/docs/install',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/manual-install': typeof DocsManualInstallRoute
  '/docs/recipe': typeof DocsRecipeRoute
  '/docs/recipes': typeof DocsRecipesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/manual-install': typeof DocsManualInstallRoute
  '/docs/recipe': typeof DocsRecipeRoute
  '/docs/recipes': typeof DocsRecipesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/docs/install': typeof DocsInstallRoute
  '/docs/manual-install': typeof DocsManualInstallRoute
  '/docs/recipe': typeof DocsRecipeRoute
  '/docs/recipes': typeof DocsRecipesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/docs/install'
    | '/docs/manual-install'
    | '/docs/recipe'
    | '/docs/recipes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/docs/install'
    | '/docs/manual-install'
    | '/docs/recipe'
    | '/docs/recipes'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/docs/install'
    | '/docs/manual-install'
    | '/docs/recipe'
    | '/docs/recipes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  DocsInstallRoute: typeof DocsInstallRoute
  DocsManualInstallRoute: typeof DocsManualInstallRoute
  DocsRecipeRoute: typeof DocsRecipeRoute
  DocsRecipesRoute: typeof DocsRecipesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/recipes': {
      id: '/docs/recipes'
      path: '/docs/recipes'
      fullPath: '/docs/recipes'
      preLoaderRoute: typeof DocsRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/recipe': {
      id: '/docs/recipe'
      path: '/docs/recipe'
      fullPath: '/docs/recipe'
      preLoaderRoute: typeof DocsRecipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/manual-install': {
      id: '/docs/manual-install'
      path: '/docs/manual-install'
      fullPath: '/docs/manual-install'
      preLoaderRoute: typeof DocsManualInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/install': {
      id: '/docs/install'
      path: '/docs/install'
      fullPath: '/docs/install'
      preLoaderRoute: typeof DocsInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  DocsInstallRoute: DocsInstallRoute,
  DocsManualInstallRoute: DocsManualInstallRoute,
  DocsRecipeRoute: DocsRecipeRoute,
  DocsRecipesRoute: DocsRecipesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
